const Resdata = [
  {
    name: "Bella Italia",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Labore magnam et autem deleniti fuga temporibus error dolore iure obcaecati libero quis perspiciatis vero expedita ab atque, pariatur exercitationem laborum saepe delectus id. Delectus dolor laborum tenetur fugiat optio, deserunt ducimus veritatis veniam recusandae quam adipisci, nesciunt rerum assumenda voluptates iusto.",
    email: "bella.italia@email.com",
    password: "BellaItalia@123",
    Street: "1234 Wilshire Blvd",
    city: "Mandi Dabwali",
    state: "Haryana",
    zip: "125104",
    phone: "123456789",
  },
  {
    name: "The Fat Duck",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Labore magnam et autem deleniti fuga temporibus error dolore iure obcaecati libero quis perspiciatis vero expedita ab atque, pariatur exercitationem laborum saepe delectus id. Delectus dolor laborum tenetur fugiat optio, deserunt ducimus veritatis veniam recusandae quam adipisci, nesciunt rerum assumenda voluptates iusto.",
    email: "thefatduck@email.com",
    password: "TheFatDuck@123",
    Street: "1234 Wilshire Blvd",
    city: "Mandi Dabwali",
    state: "Haryana",
    zip: "125104",
    phone: "123456789",
  },
  {
    name: "Din Tai Fung",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Labore magnam et autem deleniti fuga temporibus error dolore iure obcaecati libero quis perspiciatis vero expedita ab atque, pariatur exercitationem laborum saepe delectus id. Delectus dolor laborum tenetur fugiat optio, deserunt ducimus veritatis veniam recusandae quam adipisci, nesciunt rerum assumenda voluptates iusto.",
    email: "dintaifung@email.com",
    password: "DinTaiFung@123",
    Street: "789 George Street",
    city: "Chandigarh",
    state: "Punjab",
    zip: "133301",
    phone: "123456789",
  },
  {
    name: "Tetsuya's",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Labore magnam et autem deleniti fuga temporibus error dolore iure obcaecati libero quis perspiciatis vero expedita ab atque, pariatur exercitationem laborum saepe delectus id. Delectus dolor laborum tenetur fugiat optio, deserunt ducimus veritatis veniam recusandae quam adipisci, nesciunt rerum assumenda voluptates iusto.",
    email: "tetsuyas@email.com",
    password: "Tetsuya@123",
    Street: "123 Main Street",
    city: "Bathinda",
    state: "Punjab",
    zip: "151001",
    phone: "123456789",
  },
  {
    name: "Chez Panisse",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Labore magnam et autem deleniti fuga temporibus error dolore iure obcaecati libero quis perspiciatis vero expedita ab atque, pariatur exercitationem laborum saepe delectus id. Delectus dolor laborum tenetur fugiat optio, deserunt ducimus veritatis veniam recusandae quam adipisci, nesciunt rerum assumenda voluptates iusto.",
    email: "chez.panisse@email.com",
    password: "ChezPanisse@123",
    Street: "123 Main Street",
    city: "Bathinda",
    state: "Punjab",
    zip: "151001",
    phone: "123456789",
  },
  {
    name: "Bella Italia",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Labore magnam et autem deleniti fuga temporibus error dolore iure obcaecati libero quis perspiciatis vero expedita ab atque, pariatur exercitationem laborum saepe delectus id. Delectus dolor laborum tenetur fugiat optio, deserunt ducimus veritatis veniam recusandae quam adipisci, nesciunt rerum assumenda voluptates iusto.",
    email: "bella.italia@email.com",
    password: "BellaItalia@123",
    Street: "1234 Wilshire Blvd",
    city: "Mandi Dabwali",
    state: "Haryana",
    zip: "125104",
    phone: "123456789",
  },
  {
    name: "The Fat Duck",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Labore magnam et autem deleniti fuga temporibus error dolore iure obcaecati libero quis perspiciatis vero expedita ab atque, pariatur exercitationem laborum saepe delectus id. Delectus dolor laborum tenetur fugiat optio, deserunt ducimus veritatis veniam recusandae quam adipisci, nesciunt rerum assumenda voluptates iusto.",
    email: "thefatduck@email.com",
    password: "TheFatDuck@123",
    Street: "1234 Wilshire Blvd",
    city: "Mandi Dabwali",
    state: "Haryana",
    zip: "125104",
    phone: "123456789",
  },
  {
    name: "Din Tai Fung",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Labore magnam et autem deleniti fuga temporibus error dolore iure obcaecati libero quis perspiciatis vero expedita ab atque, pariatur exercitationem laborum saepe delectus id. Delectus dolor laborum tenetur fugiat optio, deserunt ducimus veritatis veniam recusandae quam adipisci, nesciunt rerum assumenda voluptates iusto.",
    email: "dintaifung@email.com",
    password: "DinTaiFung@123",
    Street: "789 George Street",
    city: "Chandigarh",
    state: "Punjab",
    zip: "133301",
    phone: "123456789",
  },
  {
    name: "Tetsuya's",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Labore magnam et autem deleniti fuga temporibus error dolore iure obcaecati libero quis perspiciatis vero expedita ab atque, pariatur exercitationem laborum saepe delectus id. Delectus dolor laborum tenetur fugiat optio, deserunt ducimus veritatis veniam recusandae quam adipisci, nesciunt rerum assumenda voluptates iusto.",
    email: "tetsuyas@email.com",
    password: "Tetsuya@123",
    Street: "123 Main Street",
    city: "Bathinda",
    state: "Punjab",
    zip: "151001",
    phone: "123456789",
  },
  {
    name: "Chez Panisse",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Labore magnam et autem deleniti fuga temporibus error dolore iure obcaecati libero quis perspiciatis vero expedita ab atque, pariatur exercitationem laborum saepe delectus id. Delectus dolor laborum tenetur fugiat optio, deserunt ducimus veritatis veniam recusandae quam adipisci, nesciunt rerum assumenda voluptates iusto.",
    email: "chez.panisse@email.com",
    password: "ChezPanisse@123",
    Street: "123 Main Street",
    city: "Bathinda",
    state: "Punjab",
    zip: "151001",
    phone: "123456789",
  },
];

export default Resdata;